controller_list:
  - name: fake_isaac_dvrk_arm_controller
    joints:
      - psm_yaw_joint
      - psm_pitch_back_joint
      - psm_pitch_bottom_joint
      - psm_pitch_end_joint
      - psm_main_insertion_joint
      - psm_tool_roll_joint
      - psm_tool_pitch_joint
      - psm_tool_yaw_joint
  - name: fake_isaac_dvrk_hand_controller
    joints:
      - psm_tool_roll_joint
      - psm_tool_pitch_joint
      - psm_tool_yaw_joint
      - psm_tool_gripper2_joint
initial:  # Define initial robot poses.
  - group: isaac_dvrk_arm
    pose: home