# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: isaac_dvrk_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - psm_yaw_joint
    - psm_pitch_back_joint
    - psm_pitch_bottom_joint
    - psm_pitch_end_joint
    - psm_main_insertion_joint
    - psm_tool_roll_joint
    - psm_tool_pitch_joint
    - psm_tool_yaw_joint
    - psm_tool_gripper2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - psm_yaw_joint
    - psm_pitch_back_joint
    - psm_pitch_bottom_joint
    - psm_pitch_end_joint
    - psm_main_insertion_joint
    - psm_tool_roll_joint
    - psm_tool_pitch_joint
    - psm_tool_yaw_joint
  gains:
    psm_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_pitch_back_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_pitch_bottom_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_pitch_end_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_main_insertion_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_tool_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_tool_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    psm_tool_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1